// Barrel export — import DB utilities from '@/lib/db'
export { getDB, checkDBHealth, ArcMakerDB } from './db';
export { MIGRATIONS, CURRENT_SCHEMA_VERSION } from './migrations';
export type {
  UserProfile,
  Campaign,
  CampaignEvent,
  Assignment,
  FieldSession,
  ActiveSessionState,
  FieldNote,
  PlannedShot,
  CapturedShot,
  Character,
  BusinessLead,
  SessionReport,
  Deliverable,
  ImportReview,
  StagedRecord,
  StagedRecordData,
  StagedObjectType,
  CampaignExport,
  ExtractedFacts,
  AiSuggestions,
  OwnedRecord,
  BaseRecord,
  CampaignStatus,
  RecordSource,
  SessionStatus,
  CharacterStatus,
  LeadStatus,
  ShotStatus,
  DeliverableFormat,
  DeliverableStatus,
  NoteType,
  ImportReviewStatus,
  AssignmentStatus,
} from './types';
